# Generated by Django 5.1.5 on 2025-01-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('property_type_area', models.CharField(max_length=255)),
                ('property_status', models.CharField(max_length=255)),
                ('service_required_on', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requirement', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
