# Generated by Django 5.1.5 on 2025-02-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
